table customers_manual
	lineageTag: af543e9d-cbcf-4b16-b957-d3a3418683c3

	column CustomerID
		dataType: int64
		formatString: 0
		lineageTag: 62c742c1-7eb5-44a5-815e-d56317c3e28a
		summarizeBy: count
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column Email
		dataType: string
		lineageTag: 4c80755c-8053-45b1-895b-ea775b12246b
		summarizeBy: none
		sourceColumn: Email

		annotation SummarizationSetBy = Automatic

	column LoyaltyLevel
		dataType: string
		lineageTag: 1f3531bc-19e1-4fd9-a14b-18295861af74
		summarizeBy: none
		sourceColumn: LoyaltyLevel

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 2c4a8cf5-e1f8-405e-8d9b-4bde68d725ae
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column BirthYear
		dataType: int64
		formatString: 0
		lineageTag: 2b8728d4-4c2f-47ea-af88-2710bbe31f25
		summarizeBy: sum
		sourceColumn: BirthYear

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: c238048d-0111-4b11-ab98-a3be3afe9f11
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	partition customers_manual = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("E:\ABC\POWER BI\MAterials\powerbi-ultimate-course\powerbi-ultimate-course\datasets\02_connection_types\masterdata_extended_1.xlsx"), null, true),
				    customers_manual_Sheet = Source{[Item="customers_manual",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(customers_manual_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"CustomerID", Int64.Type}, {"Email", type text}, {"LoyaltyLevel", type text}, {"Segment", type text}, {"BirthYear", Int64.Type}, {"Region", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

